require:
  - rubocop-rails
  - rubocop-rspec
  - rubocop-performance

inherit_from: .rubocop_todo.yml

Style/SymbolArray:
  Enabled: true

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: single_quotes

Style/FrozenStringLiteralComment:
  Enabled: true
  EnforcedStyle: always

Style/SpecialGlobalVars:
  EnforcedStyle: use_perl_names

# rubocop-rspec
RSpec/FilePath:
  CustomTransform:
    NetAM: netam

