version: '3.7'

x-aliases:
  netdiver: &netdiver
    build:
      context: .
      dockerfile: Dockerfile
    image: netdiver/netdiver
    environment:
      SECRET_KEY_BASE: v1jFMms5qurpiYdw
      DISABLE_DATABASE_ENVIRONMENT_CHECK: 1
      TYPESENSE_HOST: typesense
      TYPESENSE_API_KEY: managementkey
      SENTRY_DSN: ''
      REDIS_HOST: redis
      DB_HOST: db
      DB_NAME: netdiver
      DB_USER: admin
      DB_PASS: __CH@NG3_ME__

services:
  web:
    <<: *netdiver
    restart: always
    ports:
      - "3000:3000"

  worker:
    <<: *netdiver
    restart: always
    command: sidekiq

  redis:
    image: redis:alpine
    restart: always
    volumes:
      - redis:/data

  db:
    image: postgres:12-alpine
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: __CH@NG3_ME__
      POSTGRES_DB: netdiver
    volumes:
      - db:/var/lib/postgresql/data

  typesense:
    image: typesense/typesense:0.19.0
    restart: always
    environment:
      TYPESENSE_DATA_DIR: /data
      TYPESENSE_API_KEY: managementkey
      TYPESENSE_ENABLE_CORS: 'true'
    volumes:
      - typesense:/data

volumes:
  db:
  redis:
  typesense:
