version: '3.7'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: netam
    restart: always
    environment:
      REDIS_HOST: redis
      DB_HOST: db
      DB_NAME: netam_development
    ports:
      - "3000:3000"

  worker:
    build:
      context: .
      dockerfile: Dockerfile
    image: netam
    restart: always
    environment:
      REDIS_HOST: redis
      DB_HOST: db
      DB_NAME: netam_development
    command: sidekiq

  redis:
    image: redis:alpine
    restart: always
    ports:
      - 6379:6379

  redis-commander:
    image: rediscommander/redis-commander:latest
    restart: always
    ports:
      - "8082:8081"
    environment:
      - REDIS_HOSTS=local:redis:6379

  db:
    image: postgres:alpine
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: netam_development
