# Documentation site configuration
site_name: NetDiver-OSS
site_url: https://netdiver-oss.github.io/NetAM/
site_description: Documentation for Network Address Manager software
site_author: NetDiver-OSS

# Documentation repository configuration
repo_name: GitHub
repo_url: https://github.com/NetDiver-OSS/NetAM/
edit_uri: edit/dev/docs/

# Theme configuration
theme:
  name: flatly

# Markdown extensions configurations
markdown_extensions:
  - smarty
  - toc:
      permalink: True
      separator: "_"
  - sane_lists

# Plugins configurations
plugins:
  - search:
      min_search_lenght: 2

# Navigation configuration
nav:
  - Home: index.md
  - NetAM:
    - Architecture: architecture/index.md
    - Configuration: configuration/index.md
    - Usage: usage/index.md
    - Administration: admin/index.md
    - API: api/index.md

  - License: license.md
