has_changelog_changes = !git.modified_files.grep(/changelog\/unreleased/).empty?

# --------------------------------------------------------------------------------------------------------------------
# You've didn't write any changelog?
# --------------------------------------------------------------------------------------------------------------------
warn "There're changes, but no changelog." unless has_changelog_changes
