default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= Rails.configuration.netdiver[:db][:pool] %>
  host: <%= Rails.configuration.netdiver[:db][:host] %>
  port: <%= Rails.configuration.netdiver[:db][:port] %>
  username: <%= Rails.configuration.netdiver[:db][:username] %>
  password: <%= Rails.configuration.netdiver[:db][:password] %>
  database: <%= Rails.configuration.netdiver[:database] %>


development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
