default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= Rails.configuration.netam[:db][:pool] %>
  host: <%= Rails.configuration.netam[:db][:host] %>
  port: <%= Rails.configuration.netam[:db][:porst] %>
  username: <%= Rails.configuration.netam[:db][:username] %>
  password: <%= Rails.configuration.netam[:db][:password] %>

development:
  <<: *default
  database: <%= Rails.configuration.netam[:db][:database] %>

test:
  <<: *default
  database: <%= Rails.configuration.netam[:db][:database] %>

production:
  <<: *default
  database: <%= Rails.configuration.netam[:db][:database] %>
