## Authorizations
authorizations: &AUTHORIZATIONS
  allow_unauthenticated_bind: false
  group_base: ou=groups,dc=svk,dc=gs
  required_groups:
    - cn=ipam,ou=groups,dc=svk,dc=gs
  require_attribute:
    objectClass: inetOrgPerson
  require_attribute_presence:
    mail: true

## Environment

development:
  host: 172.16.0.100
  port: 389
  attribute: uid
  base: ou=people,dc=svk,dc=gs
  admin_user: <%= ENV['LDAP_ADMIN_USER'] %>
  admin_password: <%= ENV['LDAP_ADMIN_PASSWORD'] %>
  ssl: false
  <<: *AUTHORIZATIONS

test:
  host: localhost
  port: 3389
  attribute: uid
  base: ou=people,dc=svk,dc=gs
  admin_user: cn=admin,dc=test,dc=com
  admin_password: admin_password
  ssl: simple_tls
  # <<: *AUTHORIZATIONS

production:
  host: localhost
  port: 636
  attribute: uid
  base: ou=people,dc=svk,dc=gs
  admin_user: cn=admin,dc=test,dc=com
  admin_password: admin_password
  ssl: start_tls
  # <<: *AUTHORIZATIONS
