---
default: &default
  auth:
    ldap:
      host: <%= ENV.fetch("LDAP_HOST") { 'localhost' } %>
      port: <%= ENV.fetch("LDAP_PORT") { 389 } %>
      encryption: <%= ENV.fetch("LDAP_ENCRYPTION") { false } %>
      base: <%= ENV.fetch("LDAP_BASE") { 'dc=example,dc=com' } %>
      uid: <%= ENV.fetch("LDAP_UID") { 'uid' } %>
      bind_dn: <%= ENV.fetch("LDAP_BIND_USER") { 'cn=admin,dc=example,dc=com' } %>
      password: <%= ENV.fetch("LDAP_BIND_PASSWORD") { 'password' } %>

  sentry:
    dsn: <%= ENV.fetch("SENTRY_DSN") { 'https://5fb75d25f91e4265bdb126411b8c28b9:65c52a37f3be4598bfea096fac5c88f6@sentry.app.svk.gs/4' } %>

  redis:
    host: <%= ENV.fetch("REDIS_HOST") { 'localhost' } %>
    port: <%= ENV.fetch("REDIS_PORT") { 6379 } %>
    db: <%= ENV.fetch("REDIS_DB") { 0 } %>

  db:
    pool: <%= ENV.fetch("DB_MAX_THREADS") { 50 } %>
    host: <%= ENV.fetch("DB_HOST") { 'localhost' } %>
    port: <%= ENV.fetch("DB_PORT") { 5432 } %>
    username: <%= ENV.fetch("DB_USER") { 'admin' } %>
    password: <%= ENV.fetch("DB_PASS") { 'password' } %>

  puma:
    max_thread: <%= ENV.fetch("PUMA_MAX_THREADS") { 5 } %>
    min_thread: <%= ENV.fetch("PUMA_MIN_THREADS") { 1 } %>
    port: <%= ENV.fetch("PUMA_PORT") { 3000 } %>

  sidekiq:
    threads: <%= ENV.fetch("SIDEKIQ_MAX_THREADS") { 5 } %>
    parallel: <%= ENV.fetch("SIDEKIQ_PARALLEL") { 20 } %>

  otp:
    secret: <%= ENV.fetch("OTP_SECRET") { 'ch@ngeMech@ngeMech@ngeMech@ngeMe' } %>

  notification:
    slack_webhook: <%= ENV.fetch("SLACK_WEBHOOK") { nil } %>
    msteams_webhook: <%= ENV.fetch("MSTEAMS_WEBHOOK") { nil } %>
    mail:
      host: <%= ENV.fetch("MAIL_HOST") { nil } %>
      port: <%= ENV.fetch("MAIL_POST") { nil } %>
      user: <%= ENV.fetch("MAIL_USER") { nil } %>
      pass: <%= ENV.fetch("MAIL_PASS") { nil } %>
      type: <%= ENV.fetch("MAIL_AUTH_TYPE") { nil } %>
      helo: <%= ENV.fetch("MAIL_HELO") { nil } %>
      ssl:  <%= ENV.fetch("MAIL_SSL_ENABLE") { nil } %>
      from: <%= ENV.fetch("MAIL_FROM") { 'NetAM <no-reply@example.loc>' } %>
      to:
        - <%= ENV.fetch("MAIL_TO") { 'netam@example.loc' } %>

development:
  <<: *default
  database: <%= ENV.fetch("DB_NAME") { 'netam_development' } %>

test:
  <<: *default
  database: <%= ENV.fetch("DB_NAME") { 'netam_test' } %>

production:
  <<: *default
  database: <%= ENV.fetch("DB_NAME") { 'netam' } %>
