name: Crowdin

on:
  push:
    branches:
      - l10n_dev

jobs:
  gettext:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.CROWDIN_SECRET }}
      - name: Set up Ruby
        uses: ruby/setup-ruby@master
        with:
          ruby-version: '3.0.0'
          bundler-cache: true
      - name: Run tests
        run: |
          bundle exec rake gettext:po_to_json
        env:
          RAILS_ENV: test
      - name: Commit files
        continue-on-error: true
        run: |
          git config --local user.email "contact@sdeu.fr"
          git config --local user.name "NetAM-Bot"
          git add app/assets/javascripts/locale
          git commit -am "feat: Update gettext for javascript"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.CROWDIN_SECRET }}
          branch: ${{ github.ref }}
