name: Crowdin

on:
  push:
    branches:
      - l10n_dev

jobs:
  gettext:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - name: Set up Ruby
        uses: ruby/setup-ruby@master
        with:
          ruby-version: '2.7.2'
          bundler-cache: true
      - name: Run tests
        run: |
          bundle exec rake gettext:po_to_json
        env:
          RAILS_ENV: test
      - name: Commit & Push changes
        uses: actions-js/push@master
        with:
          message: "feat: Update gettext for javascript"
          github_token: ${{ secrets.GITHUB_TOKEN }}
