name: Publish docs on GitHub Pages
on:
  push:
    branches:
      - dev

jobs:
  build:
    name: Deploy docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master
        uses: actions/checkout@v3.0.0

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2.2.2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ${GITHUB_WORKSPACE}/mkdocs-requirements.txt

      - name: Setup git repository
        run: |
          git config --global user.name "${GITHUB_ACTOR}"
          git config --global user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git remote rm origin
          git remote add origin "https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${GITHUB_REPOSITORY}.git"

      - name: Setup git repository
        run: mkdocs gh-deploy --config-file "${GITHUB_WORKSPACE}/mkdocs.yml" --force
