docker:package:
  stage: package
  image: docker:dind
  services:
    - name: docker:stable-dind
      command: [ "dockerd", "--host=unix:///var/run/docker.sock", "--host=tcp://0.0.0.0:2375", "--mtu=1450" ]
  variables:
    DOCKER_HOST: tcp://localhost:2375
  script:
    |-
      echo $CI_COMMIT_TAG > VERSION
      sed -Ei "s/\"version\": \"(.*)\"/\"version\": \"$CI_COMMIT_TAG\"/g" package.json
      # Docker
      docker build -t netam/netam:${CI_COMMIT_TAG} .
      docker login -u ${DOCKER_HUB_USER} -p ${DOCKER_HUB_TOKEN}
      docker push netam/netam:${CI_COMMIT_TAG}
  only:
    - tags
